unavailable image asset fix and available bands refresh button
openforis/collect-earth-online pull request #1207
Opened 2021-04-21 20:09 UTC by rfontanarosa

fix #1189

Available Bands was an hidden row, now it is always visible.

GeoDash didn't know the difference between an Image Asset or an Image Collection Asset, this caused errors when it requested for the Available Bands.

Instead of performing an http request to GEEG at onChange time, now the user have to click on the Refresh button to get the available bands for a specific Image Asset or Image Collection Asset.

2021-04-21 20:51 UTC, sirmspencer commented
src/js/widgetLayoutEditor.js
288-291, Dont mutate postObjects
```
const postObjects = {
	path: "getAvailableBands",
	...(isCollection ? {imageCollection: value} : {image: value})
}

1292, 1300, these are rendering the same thing.  Just pass in availableBands / availableBandsDual depending on where its used.

2021-04-26 17:37 UTC, rjsheperd commented
I noticed that our linter has been complaining about the geodash file you edited for this PR. If you wouldn't mind:

* updating the `eval` statements to `JSON.parse` and testing that GeoDash is still working properly, 
* Running `npm i -S react-resizable` and adding the `package.json` file to your PR

2021-04-28 15:01 UTC, rjsheperd commented on src/js/widgetLayoutEditor.js
> +                ...(isCollection ? {imageCollection: value} : {image: value}),
Last linter warning: `Unexpected trailing comma`

2021-04-28 16:57 UTC, sirmspencer requested changes
While I appreciate your effort to eliminate the assignment warnings, it appears we need to go over how to create immutable functions involving objects.

2021-04-29 19:28 UTC, sirmspencer requested changes
src/js/widgetLayoutEditor.js
1378, 1547, 1585 You can condense this logic.  Note that each line refers to a different state (selectedWidgetType, selectedDataType, selectedDataTypeDual)
```
const [label, placeholder, isCollection] = this.state.selectedWidgetType === "imageAsset"
    ? ["GEE Image Asset", "LANDSAT/LC8_L1T_TOA/LC81290502015036LGN00", false]
    : ["GEE Collection Image Asset", "LANDSAT/LC8_L1T_TOA", true];
```
1544 move `||` to the beginning of the next line. Its easier to find operators when they are in the front.

2021-05-03 17:35 UTC, merged