includes frontend toggle for plot and samples in collection
openforis/collect-earth-online pull request #1711
Opened 2023-12-21 19:23 UTC by jollyblondgiant

## Purpose

adds a UI element to the collection page that toggles the visibility of the plot boundary or samples

## Related Issues

Closes COL-639

## Submission Checklist

- [x ] Included Jira issue in the PR title (e.g. `COL-### Did something here`)
- [ x] Code passes linter rules for each file you updated. To lint all files at once, run `npm run lint`. To just lint one specific file run `npx quick-lint-js src/js/<file-you-changed> --snarky`.
- [ x] No new reflection warnings (`clojure -M:check-reflection`)

## Testing

### Module Impacted
Collection

### Role

Admin

### Steps

Navigate to the collection page of an open project. observe the "show/hide plot/samples" buttons in the "External Tools." Enjoy a moment of serenity. Click the button.

1.

### Desired Outcome

observe the plot boundary and samples toggle visibility

## Screenshots

2024-01-05 14:46 UTC, a-luz requested changes
These changes work as expected!

2024-01-05 14:46 UTC, a-luz commented on src/js/utils/mercator.js
> +      id: "unanalyzedn",
Fix typo

2024-01-09 19:46 UTC, jollyblondgiant commented on src/js/utils/mercator.js
> +      id: "unanalyzedn",
fixed, thanks

2024-01-16 22:46 UTC, a-luz approved these changes

2024-01-16 22:50 UTC, merged